# 配置股票相关的参数
stock:
  inner: # A股  在yml配置文件中-表示存储到集合中的数据。inner表示存储数据的集合名，集合长度是2，数据是：sh000001 sz399001
    - sh000001 # 上证ID
    - sz399001 #  深证ID
  outer: # 外盘
    - int_dji # 道琼斯
    - int_nasdaq # 纳斯达克
    - int_hangseng # 恒生
    - int_nikkei # 日经指数
    - b_FSSTI # 新加坡
  upDownRange: # 统计涨幅区间的集合数据
    - "<-7%"
    - "-7~-5%"
    - "-5~-3%"
    - "-3~0%"
    - "0~3%"
    - "3~5%"
    - "5~7%"
    - ">7%"