# 配置股票相关的参数
stock:
  inner: # A股 在yml文件中-表示数组，我们可以放到集合中
    - sh000001 # 上证ID
    - sz399001 #  深证ID
  outer: # 外盘
    - int_dji # 道琼斯
    - int_nasdaq # 纳斯达克
    - int_hangseng # 恒生
    - int_nikkei # 日经指数
    - b_FSSTI # 新加坡
  # marketUrl表示国内大盘地址http://hq.sinajs.cn/list=sh000001,sz399001
  # 等号右边是变化的因此这里只配置到大盘编码位置
  marketUrl: http://hq.sinajs.cn/list=
  blockUrl: http://vip.stock.finance.sina.com.cn/q/view/newSinaHy.php #板块地址